apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  backend:
    serviceName: deck
    servicePort: 80
  rules:
  - host: prow.maistra.io
    http:
      paths:
      - path: /
        backend:
          serviceName: deck
          servicePort: 80
      - path: /hook
        backend:
          serviceName: hook
          servicePort: 8888
  tls:
  - hosts:
    - prow.maistra.io
    secretName: prow.maistra.io-cert
